onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_riscv_lite/RISCV_inst/CLK
add wave -noupdate /tb_riscv_lite/RISCV_inst/RSTn
add wave -noupdate /tb_riscv_lite/RISCV_inst/mem_rdy_IM
add wave -noupdate /tb_riscv_lite/RISCV_inst/mem_rdy_DM
add wave -noupdate /tb_riscv_lite/RISCV_inst/valid_IM
add wave -noupdate /tb_riscv_lite/RISCV_inst/valid_DM
add wave -noupdate /tb_riscv_lite/RISCV_inst/proc_req_IM
add wave -noupdate /tb_riscv_lite/RISCV_inst/proc_req_DM
add wave -noupdate /tb_riscv_lite/RISCV_inst/addr_IM
add wave -noupdate /tb_riscv_lite/RISCV_inst/addr_DM
add wave -noupdate /tb_riscv_lite/RISCV_inst/we_IM
add wave -noupdate /tb_riscv_lite/RISCV_inst/we_DM
add wave -noupdate /tb_riscv_lite/RISCV_inst/wdata_IM
add wave -noupdate /tb_riscv_lite/RISCV_inst/wdata_DM
add wave -noupdate /tb_riscv_lite/RISCV_inst/rdata_IM
add wave -noupdate /tb_riscv_lite/RISCV_inst/rdata_DM
add wave -noupdate /tb_riscv_lite/RISCV_inst/sPrediction
add wave -noupdate /tb_riscv_lite/RISCV_inst/sCorrection
add wave -noupdate /tb_riscv_lite/RISCV_inst/sNext_address
add wave -noupdate /tb_riscv_lite/RISCV_inst/sTarget
add wave -noupdate /tb_riscv_lite/RISCV_inst/REGwrite
add wave -noupdate /tb_riscv_lite/RISCV_inst/ALUSrc1
add wave -noupdate /tb_riscv_lite/RISCV_inst/ALUSrc2
add wave -noupdate /tb_riscv_lite/RISCV_inst/MemToReg
add wave -noupdate /tb_riscv_lite/RISCV_inst/ALUControl
add wave -noupdate /tb_riscv_lite/RISCV_inst/MemWrite
add wave -noupdate /tb_riscv_lite/RISCV_inst/MemRead
add wave -noupdate /tb_riscv_lite/RISCV_inst/sel_mux_ALU
add wave -noupdate /tb_riscv_lite/RISCV_inst/ALUOp
add wave -noupdate /tb_riscv_lite/RISCV_inst/opcode
add wave -noupdate /tb_riscv_lite/RISCV_inst/ALU_result_sign
add wave -noupdate /tb_riscv_lite/RISCV_inst/ALU_result_zero
add wave -noupdate /tb_riscv_lite/RISCV_inst/branch_inst
add wave -noupdate /tb_riscv_lite/RISCV_inst/jump_inst
add wave -noupdate /tb_riscv_lite/RISCV_inst/flush
add wave -noupdate /tb_riscv_lite/RISCV_inst/reg_pipe2_ALUOp
add wave -noupdate /tb_riscv_lite/RISCV_inst/ff_pipe2_branch_inst
add wave -noupdate /tb_riscv_lite/RISCV_inst/ff_pipe2_jump_inst
add wave -noupdate /tb_riscv_lite/RISCV_inst/ff_pipe2_MemRead
add wave -noupdate /tb_riscv_lite/RISCV_inst/ff_pipe2_MemtoReg
add wave -noupdate /tb_riscv_lite/RISCV_inst/ff_pipe2_MemWrite
add wave -noupdate /tb_riscv_lite/RISCV_inst/ff_pipe2_ALUSrc1
add wave -noupdate /tb_riscv_lite/RISCV_inst/ff_pipe2_ALUSrc2
add wave -noupdate /tb_riscv_lite/RISCV_inst/ff_pipe2_RegWrite
add wave -noupdate /tb_riscv_lite/RISCV_inst/sel_adder_MUX
add wave -noupdate /tb_riscv_lite/RISCV_inst/ff_pipe2_sel_adder_MUX
add wave -noupdate /tb_riscv_lite/RISCV_inst/reg_pipe2_sel_MUX_ALU
add wave -noupdate /tb_riscv_lite/RISCV_inst/reg_pipe2_funct7_3
add wave -noupdate /tb_riscv_lite/RISCV_inst/reg_pipe3_funct7_3
add wave -noupdate /tb_riscv_lite/RISCV_inst/ff_pipe3_branch_inst
add wave -noupdate /tb_riscv_lite/RISCV_inst/ff_pipe3_jump_inst
add wave -noupdate /tb_riscv_lite/RISCV_inst/ff_pipe3_MemRead
add wave -noupdate /tb_riscv_lite/RISCV_inst/ff_pipe3_MemtoReg
add wave -noupdate /tb_riscv_lite/RISCV_inst/ff_pipe3_MemWrite
add wave -noupdate /tb_riscv_lite/RISCV_inst/ff_pipe3_RegWrite
add wave -noupdate /tb_riscv_lite/RISCV_inst/ff_pipe4_MemtoReg
add wave -noupdate /tb_riscv_lite/RISCV_inst/ff_pipe4_RegWrite
add wave -noupdate /tb_riscv_lite/RISCV_inst/done_fetcher
add wave -noupdate /tb_riscv_lite/RISCV_inst/done_LSU
add wave -noupdate /tb_riscv_lite/RISCV_inst/busy_LSU
add wave -noupdate /tb_riscv_lite/RISCV_inst/reg_enable_fetcher
add wave -noupdate /tb_riscv_lite/RISCV_inst/reg_enable_LSU
add wave -noupdate /tb_riscv_lite/RISCV_inst/reg_enable
add wave -noupdate /tb_riscv_lite/RISCV_inst/rd_mem
add wave -noupdate /tb_riscv_lite/RISCV_inst/rd_wb
add wave -noupdate /tb_riscv_lite/RISCV_inst/rs1_ex
add wave -noupdate /tb_riscv_lite/RISCV_inst/rs2_ex
add wave -noupdate /tb_riscv_lite/RISCV_inst/forward_Src1
add wave -noupdate /tb_riscv_lite/RISCV_inst/selection_Src1
add wave -noupdate /tb_riscv_lite/RISCV_inst/forward_Src2
add wave -noupdate /tb_riscv_lite/RISCV_inst/selection_Src2
add wave -noupdate /tb_riscv_lite/RISCV_inst/pc_plus4_to_bpu
add wave -noupdate /tb_riscv_lite/RISCV_inst/computed_address
add wave -noupdate /tb_riscv_lite/RISCV_inst/data_in_code_mem
add wave -noupdate /tb_riscv_lite/RISCV_inst/inst_code_mem_out
add wave -noupdate /tb_riscv_lite/RISCV_inst/pc
add wave -noupdate /tb_riscv_lite/RISCV_inst/write_data_mem
add wave -noupdate /tb_riscv_lite/RISCV_inst/out_data_mem
add wave -noupdate /tb_riscv_lite/RISCV_inst/address_data_mem
add wave -noupdate /tb_riscv_lite/RISCV_inst/ID_EX_RegRd
add wave -noupdate /tb_riscv_lite/RISCV_inst/IF_ID_RegRs1
add wave -noupdate /tb_riscv_lite/RISCV_inst/IF_ID_RegRs2
add wave -noupdate /tb_riscv_lite/RISCV_inst/HDU_Ctrl
add wave -noupdate /tb_riscv_lite/RISCV_inst/ff_pipe_pred
add wave -noupdate /tb_riscv_lite/RISCV_inst/ff_pipe2_pred
add wave -noupdate /tb_riscv_lite/RISCV_inst/ff_pipe3_pred
add wave -noupdate /tb_riscv_lite/RISCV_inst/old_pred
add wave -noupdate /tb_riscv_lite/RISCV_inst/reg_pipe_add
add wave -noupdate /tb_riscv_lite/RISCV_inst/reg_pipe2_add
add wave -noupdate /tb_riscv_lite/RISCV_inst/reg_pipe3_add
add wave -noupdate /tb_riscv_lite/RISCV_inst/old_add
add wave -noupdate /tb_riscv_lite/mem_inst/CLK
add wave -noupdate /tb_riscv_lite/mem_inst/RSTn
add wave -noupdate /tb_riscv_lite/mem_inst/PROC_REQ
add wave -noupdate /tb_riscv_lite/mem_inst/MEM_RDY
add wave -noupdate /tb_riscv_lite/mem_inst/ADDR
add wave -noupdate /tb_riscv_lite/mem_inst/WE
add wave -noupdate /tb_riscv_lite/mem_inst/WDATA
add wave -noupdate /tb_riscv_lite/mem_inst/RDATA
add wave -noupdate /tb_riscv_lite/mem_inst/VALID
add wave -noupdate /tb_riscv_lite/mem_inst/sState
add wave -noupdate /tb_riscv_lite/mem_inst/CSn
add wave -noupdate /tb_riscv_lite/mem_inst/we_reg
add wave -noupdate /tb_riscv_lite/mem_inst/addr_reg
add wave -noupdate /tb_riscv_lite/mem_inst/wdata_reg
add wave -noupdate /tb_riscv_lite/mem_inst/rdata_reg
add wave -noupdate /tb_riscv_lite/mem_inst/MEM/clk0
add wave -noupdate /tb_riscv_lite/mem_inst/MEM/csb0
add wave -noupdate /tb_riscv_lite/mem_inst/MEM/web0
add wave -noupdate /tb_riscv_lite/mem_inst/MEM/addr0
add wave -noupdate /tb_riscv_lite/mem_inst/MEM/din0
add wave -noupdate /tb_riscv_lite/mem_inst/MEM/dout0
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {2450 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {2216 ns} {2872 ns}
